### ISSUE TITLE
bmp image has bogus header data

### ISSUE THREAD

**Issue by dmikushin** [skeeto/bmp#3]
After creating bmp file with your header, I get "bmp image has bogus header data" from eog in Ubuntu 18.04. GIMP also cannot read the generated BMP file.

**Comment by skeeto** [comment]
What image dimensions did you use? Can you share your code that creates 
the image causing trouble?

**Comment by dmikushin** [comment]
Thanks for reply and sorry, my bad: I was fwrite'ing wrong buffer.

While looking for my bug, noticed you have the `biClrImportant` part twice in the header:

```
    /* biClrImportant */
    *p++ = 0x00;
    *p++ = 0x00;
    *p++ = 0x00;
    *p++ = 0x00;

    /* biClrImportant */
    *p++ = 0x00;
    *p++ = 0x00;
    *p++ = 0x00;
    *p   = 0x00;
```

**Comment by skeeto** [comment]
Oops, good catch, thanks!
