### ISSUE TITLE
Error in the header heigth

### ISSUE THREAD

**Issue by Raphael-Boichot** [skeeto/bmp#4]
Hello.

We are using your library in an ESP project: https://github.com/zenaro147/NeoGB-Printer
If we test your library in C or within the ESP, we get a constant error: the height bytes in the header are systematically wrong (seems to be FF FF FF FF complement). I think it have to do with the fact that you push a negative height value into the bytes (in bmp_FixedWidthStream.h, unsigned long uh = -height;).

So I have inversed the value (unsigned long uh = height;) no more header error but now the image is of course upside down ! How can we fix that ?

Regards

Raphaël

**Comment by Raphael-Boichot** [comment]
Oh, it's within the BMP specs, sorry.

**Comment by skeeto** [comment]
If you need traditional, non-negative, bottom-up BMPs, see the BMP_COMPAT 
option documented in the README. I've needed this from time to time since 
not everything can consume negative-height BMPs.

**Comment by Raphael-Boichot** [comment]
Thanks ^^
